language: node_js
os:
  - windows
  - linux
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MZ3VAR6cYWYqwF0Vz454Q8pniigTshgmvM/eKBPMqhHPSdHcxOX77828qGgO0DZFIXKlKKRwArDKVnBLfliC5z84h30adf7PozQ0JJQIrjV7pMWi9AoJW7SuguVXwIkXOiYOP++HSPDuZFxa/YpZBLJBER9WLauL4ox12f081YwAfRm/qrNOF5iOeyU8gk0i46nLC512dWhEa3vTQmL5YZotNUdRRxM0QxB5eYXgZBK6u48+ifZPoYGdQMyKq1GnR1d7B7qxP7+BCY0iIvJA0Kb1HWhsq5t6TOdTGtyDbD/ms7eqUooh7I7yIoKy6nofDVJ2P0D7AU8sbHSm4BMj6U5J9z8MxGCHXQ93G3NnqRJzzcdaog1WJy0HB8m8ZoeAYdugWgdx/+lESnvvMrzIToBl77JMXBgk3JeEdLLV2kHwBZForZ5e+yuKYVu5XcTllJ6N4UrfcZtmS22mwQMrt678hfOFf6y3bPZ+2uVpI+Wsb3H5fEdTS5LeKK1ez36vdSKl9hHFVxv9j1wRrcWhSy5b2hYWK7y+GkWZfxR+PhfvM6wMTJvwm7UC0VIHPXmAFZ5GDVtYeKAeW3vLRHLA7uSOld0BQIRS/7dPwhl9NVPM/lL0nJM4OUr7ZxYmmuilyvrCJgQL5YEvTPIvkCLQ9c8R4fTBqzdxED6rR+AZVus=
  file:
    - 'vfile-message.js'
    - 'vfile-message.min.js'
  on:
    tags: true
